CREATE DATABASE Hotel;

USE Hotel;

CREATE TABLE PersonalInfo(
	Id UNIQUEIDENTIFIER DEFAULT(newid()) PRIMARY KEY NOT NULL,
	FirstName NVARCHAR(256) NOT NULL,
	MidName NVARCHAR(256),
	LastName NVARCHAR(256) NOT NULL,
	EGN NVARCHAR(16) NOT NULL,
	ClientNumber NVARCHAR(16) 
);


CREATE TABLE Addresses(
	Id UNIQUEIDENTIFIER DEFAULT(newid()) PRIMARY KEY NOT NULL,
	PersonalInfoId UNIQUEIDENTIFIER NOT NULL,
	ZipCode NVARCHAR(256) NOT NULL,
	[Address] NVARCHAR(256) NOT NULL,
	[EXT] NVARCHAR(256)
);

CREATE TABLE AddressTags(
	Id UNIQUEIDENTIFIER DEFAULT(newid()) PRIMARY KEY NOT NULL,
	AddressId UNIQUEIDENTIFIER NOT NULL,
	[Type] INT NOT NULL
);

CREATE TABLE PhoneInfo(
	Id UNIQUEIDENTIFIER DEFAULT(newid()) PRIMARY KEY NOT NULL,
	PersonalInfoId UNIQUEIDENTIFIER NOT NULL,
	AreaCode NVARCHAR(128) NOT NULL,
	Number NVARCHAR(128) NOT NULL,
	EXT NVARCHAR(128) 
);

CREATE TABLE PhoneTags(
	Id UNIQUEIDENTIFIER DEFAULT(newid()) PRIMARY KEY NOT NULL,
	PhoneId UNIQUEIDENTIFIER NOT NULL,
	[Type] INT NOT NULL 
);

CREATE TABLE RoomInfo(
	Id UNIQUEIDENTIFIER DEFAULT(newid()) PRIMARY KEY NOT NULL,
	RoomNumber NVARCHAR(8) NOT NULL,
	[RoomType] NVARCHAR(128) NOT NULL,
	BedNumber TINYINT NOT NULL,
	FloorNumber TINYINT NOT NULL
);

CREATE TABLE ReserveInfo(
	Id UNIQUEIDENTIFIER DEFAULT(newid()) PRIMARY KEY NOT NULL,
	PersonId UNIQUEIDENTIFIER NOT NULL,
	RoomId UNIQUEIDENTIFIER NOT NULL,
	DateFrom DATE NOT NULL,
	DateTo DATE NOT NULL
);
